name: flutter_core
description: "A new Flutter project."

version: 1.0.22

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.0
  get_it: ^7.6.4
  shared_preferences: ^2.2.1
  path: ^1.8.3
  http: ^1.1.2
  logging: ^1.2.0

dev_dependencies:
  sqflite_common_ffi: ^2.3.1
  mockito: ^5.4.3
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  module:
    androidX: true
    androidPackage: com.esser.marcelo.flutter_core
    iosBundleIdentifier: com.esser.marcelo.flutterCore
